from app.core.service.email_parser.strategy.extract_data_from_file import ExtractDataFromXlsxFileService
from app.core.service.email_parser.strategy.filter_email import FilterEmailOnSubjectNameandAttachmentTypeService
from .email_parser import EmailParserService
